name: LF AI & Data Foundation Logos and Artwork
title: LF AI & Data Foundation Logos and Artwork 
description: >-
  Logos and artwork for LF AI & Data Foundation and it's hosted projects

# Settings
github_repo: https://github.com/lfai/artwork
top_logo: other/lfaidata/horizontal/white/lfaidata-horizontal-white.svg
